# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  # Azure Devops 使用 Self-Hosted Ubuntu Agent
  name: Default

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'arm-demo-conn'
    subscriptionId: '459181b5-f5ca-46b6-8e5e-e7fe26ac3635'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Spar-RG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Spar-yen/arm-template-deployment-demo/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName armdemo0912'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
